manifest: 
  version: "1.2"
  projects:
    - name: zephyr
      url: https://github.com/nrfconnect/sdk-zephyr
      revision: v3.7.99-ncs1
      clone-depth: 5
      import:
        path-prefix: deps
    - name: boards
      url: https://github.com/Siphi1239/Zephyr_boards
      import:
        path-prefix: my_boards

self: 
  path: app

